variable "resource_group" {}
variable "environment" {}
variable "location_shortcut" {}
variable "service" {}
variable "scopes" {}
#variable "description_metric" {}
variable "metric_namespace" {}
variable "aggregation" {}
variable "operator" {}
variable "email_dbaas" {}
variable "warn_cpu" {}
variable "cri_cpu" {}
variable "warn_mem" {}
variable "cri_mem" {}
variable "warn_storage" {}
variable "cri_storage" {}
variable "warn_active_con" {}
variable "cri_active_con" {}
variable "warn_failed_con" {}
variable "cri_failed_con" {}
variable "warn_log_storage" {}
variable "cri_log_storage" {}
variable "warn_io" {}
variable "cri_io" {}
